package net.brightroom.garage.web.theme

import androidx.compose.ui.graphics.Color

val md_theme_dark_primary = Color(0xFFBBC3FF)
val md_theme_dark_onPrimary = Color(0xFF1B2678)
val md_theme_dark_primaryContainer = Color(0xFF333F90)
val md_theme_dark_onPrimaryContainer = Color(0xFFDEE0FF)
val md_theme_dark_secondary = Color(0xFFC3C5DD)
val md_theme_dark_onSecondary = Color(0xFF2C2F42)
val md_theme_dark_secondaryContainer = Color(0xFF434659)
val md_theme_dark_onSecondaryContainer = Color(0xFFDFE1F9)
val md_theme_dark_tertiary = Color(0xFFE4BAD8)
val md_theme_dark_onTertiary = Color(0xFF43273D)
val md_theme_dark_tertiaryContainer = Color(0xFF5B3D55)
val md_theme_dark_onTertiaryContainer = Color(0xFFFFD7F3)
val md_theme_dark_error = Color(0xFFFFB4AB)
val md_theme_dark_onError = Color(0xFF690005)
val md_theme_dark_errorContainer = Color(0xFF93000A)
val md_theme_dark_onErrorContainer = Color(0xFFFFDAD6)
val md_theme_dark_background = Color(0xFF1B1B1F)
val md_theme_dark_onBackground = Color(0xFFE4E1E6)
val md_theme_dark_surface = Color(0xFF1B1B1F)
val md_theme_dark_onSurface = Color(0xFFE4E1E6)
val md_theme_dark_surfaceVariant = Color(0xFF46464F)
val md_theme_dark_onSurfaceVariant = Color(0xFFC6C5D0)
val md_theme_dark_outline = Color(0xFF90909A)

val StatusHealthy = Color(0xFF4CAF50)
val StatusDegraded = Color(0xFFFFC107)
val StatusUnavailable = Color(0xFFF44336)
