name: Seed Cache

on:
  push:
    branches:
      - main

permissions: {}

jobs:
  seed-cache:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    permissions:
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@d23441a48e516b6c34aea4fa41551a30e30af803 # v6.1.0
        with:
          persist-credentials: false

      - name: Build and Test
        uses: ./.github/actions/gradle-action
        with:
          command: server:check shared:jvmTest
